version: '3'
services:
  zookeeper:
    # Zookeeper, Kafka'nın çalışması için gerekli koordinasyon servisidir
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"  # Zookeeper'ın dinlediği port
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  # Kimlik doğrulama olmadan girişe izin ver

  kafka:
    # Kafka, mesaj kuyruğu (broker) servisidir
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"  # Kafka'nın dinlediği port
    environment:
      - KAFKA_BROKER_ID=1  # Broker kimliği (tek broker için 1)
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181  # Zookeeper ile bağlantı adresi
      - KAFKA_LISTENERS=PLAINTEXT://:9092  # Kafka'nın dinlediği adres
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092  # Dışarıya bildirilen adres
      - ALLOW_PLAINTEXT_LISTENER=yes  # Şifrelenmemiş bağlantıya izin ver
    depends_on:
      - zookeeper  # Kafka başlamadan önce Zookeeper başlatılır

  mongo:
    # MongoDB NoSQL veritabanı servisi
    image: mongo:6
    ports:
      - "27017:27017"  # MongoDB'nin dinlediği port
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin  # Yönetici kullanıcı adı
      - MONGO_INITDB_ROOT_PASSWORD=secret      # Yönetici şifresi